### ISSUE TITLE
Sprint 4: Feedback

### ISSUE THREAD

**Issue by samuelchassot** [favo-sdp/Favo#103]
Here is feedback similar to what we sent to other members of the SDP Staff:

The product is going great, the application is nice and the code is clean. The issue with you team is more the Scrum process that is not respected. Two members have almost no commits on master since the beginning which is bad.

@Gondolav

**Comment by muneebazam** [comment]
Hi Samuel,

I think the reason why it shows some members have no commits on master is because I and a couple others have been merging/resolving conflicts on master but thats not to say that they haven't done a considerable amount of work in their own branches, so the commits to master branch is not a good indication of how much work each person has done. 

However, going forward we will all merge our own pull requests to master so that commits from all members show up into the master branch.

Thanks

**Comment by samuelchassot** [comment]
Hi Muneeb,

I understand, but when you merge someone else's PR, the merge commit is assigned to you but all other commits keep their author. 

We will base the grade on the stats, and we asked you to all commit using **your own** account, and if you did so, we would see everyone's commits on master. 

So I remind to everyone: commit using **your own account** and remember you have to work on your feature entirely (a whole piece of functionality from backend to UI). We will use the commits to grade you.

I tag everyone to be sure that it is clear to all of you: @muneebazam @RootofalleviI @arosu @danielpgp1012 @mikanikos @huajian1069 @Gondolav 

Best,

Samuel
